clone:
  git:
    image: plugins/git
    branch: master
    depth: 32767

workspace:
  base: /build
  path: src/github.com/mephux/ruby-nessus

pipeline:
  normal:
    image: mephux/docker-golang
    environment:
      - GO15VENDOREXPERIMENT=1
    commands:
      - export GEM_HOME=$HOME/.gem
      - export GEM_PATH=$HOME/.gem
      - export PATH=$PATH:$GEM_PATH/bin
      - apk add --update rpm ruby-dev gcc make > /dev/null 2>&1
      - gem install bundler --no-rdoc --no-ri --no-document
      - bundle install --jobs=3 --retry=3
      - bundle exec rubocop -F --fail-level C -f s
      - bundle exec rspec spec
      - gem build ruby-nessus.gemspec
      - gem push ruby-nessus.gem --key=$$rubygems
    when:
      event: [push]
  dist:
    image: mephux/docker-golang
    environment:
      - GO15VENDOREXPERIMENT=1
    commands:
      - apk add --update rpm ruby-dev gcc make > /dev/null 2>&1
      - gem install yard bundler rdoc rubygems-tasks fpm rake rspec rainbow nokogiri tins --no-rdoc --no-ri --no-document
      - bundle exec rubocop -F --fail-level C -f s
      - bundle exec rspec spec
    when:
      event: [tag]
publish:
  github_release:
    api_key: $$GITHUB
    files: dist/*xz
    file_exists: fail
    # draft: true
    when:
      event: tag
